services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile
#    build:
#      context: ./app
    container_name: api
    command: sh /start-reload.sh
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
#    volumes:
#      - ./app:/app

  postgres:
    image: postgres:latest
    container_name: postgres-for-api
    ports:
      - "5432:5432"
    environment:
      POSTGRES_NAME: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 3
