"""create tables original_urls and short_urls

Revision ID: 08f86ab95ed4
Revises: 
Create Date: 2024-01-12 12:31:18.867246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f86ab95ed4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('original_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('short_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_url', sa.String(length=15), nullable=False),
    sa.Column('long_url_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['long_url_id'], ['original_urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_urls')
    op.drop_table('original_urls')
    # ### end Alembic commands ###
